# Generated by Django 4.2.11 on 2025-03-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loginmodel',
        ),
    ]
